#!/bin/bash
#SBATCH --output=/home/admin/jupyterhub_slurmspawner_%j.log
#SBATCH --job-name=spawner-jupyterhub
#SBATCH --chdir=/home/admin
#SBATCH --export=PATH,JUPYTERHUB_API_TOKEN,JPY_API_TOKEN,JUPYTERHUB_CLIENT_ID,JUPYTERHUB_COOKIE_HOST_PREFIX_ENABLED,JUPYTERHUB_HOST,JUPYTERHUB_OAUTH_CALLBACK_URL,JUPYTERHUB_OAUTH_SCOPES,JUPYTERHUB_OAUTH_ACCESS_SCOPES,JUPYTERHUB_OAUTH_CLIENT_ALLOWED_SCOPES,JUPYTERHUB_USER,JUPYTERHUB_SERVER_NAME,JUPYTERHUB_API_URL,JUPYTERHUB_ACTIVITY_URL,JUPYTERHUB_BASE_URL,JUPYTERHUB_SERVICE_PREFIX,JUPYTERHUB_SERVICE_URL,JUPYTERHUB_PUBLIC_URL,JUPYTERHUB_PUBLIC_HUB_URL,JUPYTERHUB_ROOT_DIR,JUPYTERHUB_DEFAULT_URL,JUPYTERHUB_DEBUG,USER,HOME,SHELL
#SBATCH --get-user-env=L
    
    
set -euo pipefail
    
trap 'echo SIGTERM received' TERM
    
srun batchspawner-singleuser jupyter-lab --notebook-dir=/tmp/admin/notebooks --ip=0.0.0.0 --allow-root
echo "jupyterhub-singleuser ended gracefully"
    
